services:
  # Production environment configuration
  app-prod:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
      args:
        ENV: production
    ports:
      - '5173:5173'
    env_file: '.env'
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      - PORT=5173
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - type: bind
        source: ./  # Bind the root directory to /app
        target: /app
      - type: bind
        source: ./.env.local
        target: /app/.env.local
      - type: bind
        source: ./.env
        target: /app/.env
      - node_modules:/app/node_modules
    command: pnpm run dockerstart
    profiles:
      - production
    healthcheck:
      test: curl --silent --fail http://localhost:5173 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development environment configuration
  app-dev:
    image: bolt-ai:development
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-development
      args:
        ENV: development
    ports:
      - '5174:5173'
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - type: bind
        source: ./  # Bind the root directory to /app
        target: /app
        consistency: cached
      - type: bind
        source: ./.env.local
        target: /app/.env.local
      - type: bind
        source: ./.env
        target: /app/.env
      - node_modules:/app/node_modules
    command: pnpm run dev --host 0.0.0.0
    profiles: ['development', 'default']
    healthcheck:
      test: curl --silent --fail http://localhost:5173 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# Named Volumes
volumes:
  node_modules:
    driver: local
